before_install: 
  "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz"
  "mkdir geckodriver"
  "tar -xzf geckodriver*.tar.gz -C geckodriver"
  "export PATH=$PATH:$PWD/geckodriver"
language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

after_success:
    - npm run report-coveralls
    - npm run report-codecov

