install:
- "wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz"
- "tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C bin"
- "export PATH=$(pwd)/bin:$PATH"
language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

after_success:
    - npm run report-coveralls
    - npm run report-codecov

